name: XCode

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - name: List targets
      run: xcodebuild -list -project UIKitCatalog.xcodeproj
    - name: Build
      run: xcodebuild build -target UIKitCatalog
